### ISSUE TITLE
Does it support multi tenancy?

### ISSUE THREAD

**Issue by muminoff** [bryanl/ha-minio#1]
Didn't install and test yet. But, played around with minio on my local machine. Just curious, does your solution make it multi-tenant based or just for single user?

**Comment by bweston92** [comment]
Single user.

**Comment by muminoff** [comment]
Hah, I was very new to `minio` at that time when I created this issue. Now I am in contact with it's developers in gitter.

**Comment by bweston92** [comment]
I thought I recognised your avatar aha :D
